# Task 1:

In [9]:
# 1.Write a function to compute 5/0 and use try/except to catch the exceptions.

def askint():
    try:
        v=int(input("pls try to enter an integer:"))
        w=7/v
        print(f"this code is working fine: {w}")
    except Exception as e:
        print(e)
        print("this is an issue with code")
askint()

pls try to enter an integer:0
division by zero
this is an issue with code


In [7]:
# 2.Implement a Python program to generate all sentences where subject is in ["Americans","Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"].
# Hint: Subject,Verb and Object should be declared in the program as shown below.
# subjects=["Americans ","Indians"]
# verbs=["play","watch"]
# objects=["Baseball","Cricket"]

subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]
def fun(l1,l2,l3):
    for i in l1:
        for j in l2:
            for k in l3:
                 print(i+ " "+ j+ " " +k) 
print("Output:")
print(fun(subjects,verbs,objects))

Output:
Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket
None


# OR

In [6]:
subject=["Americans","Indians"]
verb=["play","watch"]
objects=["Baseball","Cricket"]
lst = [(i+' '+j+' '+k+".") for i in subject for j in verb for k in objects]
print("Output:")
for fun in lst:    
    print(fun)

Output:
Americans play Baseball.
Americans play Cricket.
Americans watch Baseball.
Americans watch Cricket.
Indians play Baseball.
Indians play Cricket.
Indians watch Baseball.
Indians watch Cricket.


# Task 2:

In [ ]:
# 1.Write a function so that the columns of the output matrix are powers of the input vector.The order of the powers is determined by the increasing boolean argument. Specifically, when
# increasing is False, the i-th output column is the input vector raised element-wise to the power of N - i - 1.
# HINT: Such a matrix with a geometric progression in each row is named for Alexandre-Theophile Vandermonde.


In [18]:
import numpy as np
a = np.array ([1,2,3,4,5])
Y=3
print(np.vander(a, Y))
print("-"*52)
print(np.vander(a,Y, increasing=True))

[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]]
----------------------------------------------------
[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]]


# OR

In [21]:
import numpy as np
def gen_vander_matrix(input, n, increasing=False):
    
    if not increasing:
        output = np.array([x**(n-1-i) for x in input for i in range(n)]).reshape(input.size,n)
    elif increasing:
        output = np.array([x**i for x in input for i in range(n)]).reshape(input.size,n)
    
    return output

print("Output:")

input1 = np.array([1,2,3,4,5])
no_col = 3
output_dec_order = gen_vander_matrix(input1,no_col,False)
output_inc_order = gen_vander_matrix(input1,no_col,True)

print("The input array is:",input1,"\n")
print("Number of columns in output matrix should be:",no_col,"\n")
print("Vander matrix of the input array in decreasing order of powers:\n\n",output_dec_order,"\n")
print("Vander matrix of the input array in increasing order of powers:\n\n",output_inc_order,"\n")

Output:
The input array is: [1 2 3 4 5] 

Number of columns in output matrix should be: 3 

Vander matrix of the input array in decreasing order of powers:

 [[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]
 [25  5  1]] 

Vander matrix of the input array in increasing order of powers:

 [[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]
 [ 1  5 25]] 

